extract_pixstack: 600000

point_sources:
    do_measure: True
    sep_extract_kws:
        thresh: 5
        minarea: 10
        deblend_cont: 0.001
        filter_num_fwhm: 1.0
    sep_back_kws:
        bw: 128
        bh: 128
        fw: 3
        fh: 3
        fthresh: 0.0
